/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ModuleSlugRouteImport } from './routes/module.$slug'
import { Route as AiTestSynthRouteImport } from './routes/ai.test-synth'
import { Route as AiMockServerRouteImport } from './routes/ai.mock-server'
import { Route as AiDocsGenRouteImport } from './routes/ai.docs-gen'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleSlugRoute = ModuleSlugRouteImport.update({
  id: '/module/$slug',
  path: '/module/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTestSynthRoute = AiTestSynthRouteImport.update({
  id: '/ai/test-synth',
  path: '/ai/test-synth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMockServerRoute = AiMockServerRouteImport.update({
  id: '/ai/mock-server',
  path: '/ai/mock-server',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDocsGenRoute = AiDocsGenRouteImport.update({
  id: '/ai/docs-gen',
  path: '/ai/docs-gen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/monitor': typeof MonitorRoute
  '/reports': typeof ReportsRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/ai/docs-gen': typeof AiDocsGenRoute
  '/ai/mock-server': typeof AiMockServerRoute
  '/ai/test-synth': typeof AiTestSynthRoute
  '/module/$slug': typeof ModuleSlugRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/monitor': typeof MonitorRoute
  '/reports': typeof ReportsRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/ai/docs-gen': typeof AiDocsGenRoute
  '/ai/mock-server': typeof AiMockServerRoute
  '/ai/test-synth': typeof AiTestSynthRoute
  '/module/$slug': typeof ModuleSlugRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/monitor': typeof MonitorRoute
  '/reports': typeof ReportsRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/ai/docs-gen': typeof AiDocsGenRoute
  '/ai/mock-server': typeof AiMockServerRoute
  '/ai/test-synth': typeof AiTestSynthRoute
  '/module/$slug': typeof ModuleSlugRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integrations'
    | '/monitor'
    | '/reports'
    | '/scans'
    | '/settings'
    | '/ai/docs-gen'
    | '/ai/mock-server'
    | '/ai/test-synth'
    | '/module/$slug'
    | '/report/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integrations'
    | '/monitor'
    | '/reports'
    | '/scans'
    | '/settings'
    | '/ai/docs-gen'
    | '/ai/mock-server'
    | '/ai/test-synth'
    | '/module/$slug'
    | '/report/$id'
  id:
    | '__root__'
    | '/'
    | '/integrations'
    | '/monitor'
    | '/reports'
    | '/scans'
    | '/settings'
    | '/ai/docs-gen'
    | '/ai/mock-server'
    | '/ai/test-synth'
    | '/module/$slug'
    | '/report/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MonitorRoute: typeof MonitorRoute
  ReportsRoute: typeof ReportsRoute
  ScansRoute: typeof ScansRoute
  SettingsRoute: typeof SettingsRoute
  AiDocsGenRoute: typeof AiDocsGenRoute
  AiMockServerRoute: typeof AiMockServerRoute
  AiTestSynthRoute: typeof AiTestSynthRoute
  ModuleSlugRoute: typeof ModuleSlugRoute
  ReportIdRoute: typeof ReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$slug': {
      id: '/module/$slug'
      path: '/module/$slug'
      fullPath: '/module/$slug'
      preLoaderRoute: typeof ModuleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/test-synth': {
      id: '/ai/test-synth'
      path: '/ai/test-synth'
      fullPath: '/ai/test-synth'
      preLoaderRoute: typeof AiTestSynthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/mock-server': {
      id: '/ai/mock-server'
      path: '/ai/mock-server'
      fullPath: '/ai/mock-server'
      preLoaderRoute: typeof AiMockServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/docs-gen': {
      id: '/ai/docs-gen'
      path: '/ai/docs-gen'
      fullPath: '/ai/docs-gen'
      preLoaderRoute: typeof AiDocsGenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationsRoute: IntegrationsRoute,
  MonitorRoute: MonitorRoute,
  ReportsRoute: ReportsRoute,
  ScansRoute: ScansRoute,
  SettingsRoute: SettingsRoute,
  AiDocsGenRoute: AiDocsGenRoute,
  AiMockServerRoute: AiMockServerRoute,
  AiTestSynthRoute: AiTestSynthRoute,
  ModuleSlugRoute: ModuleSlugRoute,
  ReportIdRoute: ReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
